### ISSUE TITLE
A comparison with other raster data ?

### ISSUE THREAD

**Issue by gjlawran** [bcgov/bc-road-analysis#4]
**This is a cool project!**  

Would be fun to compare result with  GeoTiff  downloaded from [HectaresBC](https://hectaresbc.org/app/habc/HaBC.html?type=raster&query=linearfeat.roadlength )  .

Data there is 1 year old.

**Comment by stephhazlitt** [comment]
Thanks @gjlawran. I suspect there might be some minor differences due to the 1-year difference in the date-stamp of the Digital Road Atlas&mdash;updated versions of the DRA are released regularly under the [resource roads update project](https://www2.gov.bc.ca/gov/content?id=0B6E30C6EC5044C0850F4D019CA8222C). 

Also, there could be differences depending on whether all road types were included in the HectaresBC layer, which I would guess is the case. For this script, the [decommissioned roads and non-motorized trails were filtered out](https://github.com/bcgov/bc-raster-roads/blob/master/02_clean.R#L24-L27) first. A user can of course re-run at any time with the most up-to-date DRA and tailor the filtering for the appropriate needs of a project.

**Comment by gjlawran** [comment]
Yes , great to have repeatable documented approach to processing the data. How much time does it take to process the entire province? Any plans on sharing this resulting data as files or visualizations?

**Comment by stephhazlitt** [comment]
The scripts take a few hours to run, and can be run at any time sourcing the most up-to-date [DRA data from the B.C. Data Catalogue](https://catalogue.data.gov.bc.ca/dataset/bb060417-b6e6-4548-b837-f9060d94743e).
